apps/principal/urls.py
from django.conf.urls import url
from . import views 


urlpatterns = [
	#url(r'^$',views.IndexView.as_view(),name='index'),   
	url(r'^$', "apps.users.views.inicio"),	
	url(r'^addescuela/$',views.AddEscuela.as_view(),name='add_escuela'),
	url(r'^addalumno/$',views.AddAlumno.as_view(),name='add_alumno'),  
	url(r'^listalumno/$',views.ListAlumnos.as_view(),name='list_alumno'),  
    url(r'^expatenciones/$', 'apps.principal.views.ExportaAtenciones',name='xds'), 
    url(r'^addaten/$',views.AddAtencionViews.as_view(),name='add_atencio'),
    url(r'^buscanombre_url/$','apps.principal.views.ListaAlumnos_ajax',name='aj_busanombre'),
    url(r'^auto/$','apps.principal.views.persona_auto_complete', name='persona_auto_complete'),
    url(r'^auto_escuela/$','apps.principal.views.escuela_auto_completa', name='escuela_auto_complete'),
    url(r'^addalu_modal/$','apps.principal.views.addalumodel',name='add_alumnomodel'),
    url(r'^edad_alumno/$','apps.principal.views.edad_alumno_ajax'),
   
]
  

apps/users/urls.py
from django.conf.urls import patterns,  url

urlpatterns = patterns('',
    url(r'^login/$', 'apps.users.views.userlogin', name='login'),
    url(r'^salir/$', 'apps.users.views.LogOut', name='logout'),
    
)

hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
   
    url(r'^',include('apps.principal.urls',namespace ='principal_app')), 
    url(r'^',include('apps.users.urls',namespace='users_app')), 
   
]

apps/principal/models.py
# -*- coding: utf-8 -*-
from django.db import models 
from django.conf import settings

from datetime import date,datetime
import datetime 




class TimeStampModel(models.Model):
    user     = models.ForeignKey(settings.AUTH_USER_MODEL,db_index=True,null=True,blank=True)
    fecha    = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True) 

    class Meta:
        abstract = True


class Cicloescolar(TimeStampModel):
    descripcion = models.CharField(max_length=80)
    fechaini = models.DateField()
    fechafin = models.DateField()
    status = models.BooleanField(default=True) 

    def __unicode__(self):
        return self.descripcion


class Hospital(TimeStampModel):
    nombre = models.CharField(max_length=60)
    usuarios = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name= 'hospital_user')
       
    def __unicode__(self):
        return self.nombre

    def get_usuarios(self):
        return "\n".join([u.username for u in self.usuarios.all()])

    class Meta:
        ordering = ["pk"]


class Escuela(TimeStampModel):
    OPturno = (
        ('TV', 'Turno Vespertino'),
        ('TM', 'Turno Matutino'),
        )

    nombre = models.CharField(max_length=180)
    colonia = models.CharField(max_length=180)
    direccion = models.CharField(max_length=120, null=True, blank=True)
    localidad = models.CharField(max_length=100)
    turno = models.CharField(max_length=2, null=True, blank=True,choices=OPturno)

    def __unicode__(self):
        return self.nombre

    def seave(self, force_insert=False, force_update=False):
        self.nombre = self.nombre.lower()
        super(Escuela, self).save(force_insert, force_update)


 
class Alumno(models.Model):
  
    nombre = models.CharField(max_length=180,db_index=True) #   
    sexo = models.CharField(max_length=1, null=True, blank=True) #
    colonia = models.CharField(max_length=100,null=True, blank=True) #
    callenum = models.CharField(max_length=100,null=True, blank=True) #
    localidad = models.CharField(max_length=80,null=True, blank=True) #
    discapacidad = models.CharField(max_length=12,null=True, blank=True) #
    escolaridad = models.CharField(max_length=40,null=True, blank=True) #
    fechanaciomiento = models.DateField()
  
     
    def __unicode__(self):
        return self.nombre
 
    def edad(self):
        import datetime
        today = datetime.date.today()
        #return  ((today.year - self.fechanaciomiento.year-1)+(1 if(today.month, today.day)>=(self.fechanaciomiento.month, self.fechanaciomiento.day) else 0))
        return today.year - self.fechanaciomiento.year + (today.month-self.fechanaciomiento.month)/12

    def mes(self):
        import datetime
        today = datetime.date.today()
        #today = datetime.date(2016, 10, 6)  # aqui  pongo a  fecha que se me da la gana no solo la  de  hoy
        #return today.year - self.fechanaciomiento.year + (today.month-self.fechanaciomiento.month)/12,  (today.month-self.fechanaciomiento.month)%12 # año y mes
        return (today.month-self.fechanaciomiento.month)%12  # solo Mes
 
 


    #def save(self, force_insert=False, force_update=False):
    #    self.nombre = self.nombre.lower()
    #    super(Alumno, self).save(force_insert, force_update)

    #def clean(self):
    #    if self.nombre:
    #        self.nombre = self.nombre.strip()



 
class Atencion(TimeStampModel):
      
    tp =(
            ('Pediatria','Pediatria'),
            ('ConsultaExt','Consulta Externa'),
            ('AtencionDom','Atencion Domiciliaria'),
        )
    
    at = (
            ('Pedagogia','Pedagogia'),
            ('Psicologia','Psicologia'),
        )

    hospital = models.ForeignKey('Hospital')  
    alumno = models.ForeignKey('Alumno') 
    ciclo = models.ForeignKey('Cicloescolar')
    atencion = models.CharField(max_length=10,null=True,blank=True,choices=at)     
    modalidad = models.CharField(max_length=25,null=True,default=True,choices=tp)
    edad = models.IntegerField(default=0) #
    meses = models.IntegerField(default=0) #
    grado = models.IntegerField(default=0) 
    especialidad = models.CharField(max_length=80)
    diagnostico = models.CharField(max_length=80)
    fechaatencion  = models.DateField()
    horainicio = models.TimeField(default=datetime.datetime.utcnow,null=True,blank=True)
    horafin = models.TimeField(default=datetime.datetime.utcnow,null=True,blank=True)   
    tema = models.CharField(max_length=80,default="xxx", null=True,blank=True)
    observacion = models.TextField(default="xxx",null=True,blank=True)
    
    
    def __unicode__(self):
        return self.alumno.nombre   

    

apps/principal/forms.py
#encoding:utf-8
from django import forms
from models import Alumno,Atencion,Escuela  

 

#from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget


class AddAtencionForm(forms.ModelForm):
	class Meta:
		model = Atencion
		exclude = ['ciclo','user'] 

        persona_display = forms.CharField(max_length=180,widget=forms.TextInput(attrs={'placeholder':'Nombre de alumno','size': '40','class':'form-control'}))
        observacion = forms.CharField(widget=forms.Textarea(attrs={'rows':'2', 'cols': '40'})) 
        grado = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': 'Grado','min': '0', 'max':'6'}))
        especialidad = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Especialidad','size': '40'}))
        diagnostico = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Diagnostico','size': '40'}))
        tema = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Tema','size': '40'}))
        horainicio = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'hh:mm:ss'}))
        #horainicio = forms.TimeField(widget=TimeWidget)
        horafin = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'hh:mm:ss'}))
        fechaatencion = forms.DateField(('%Y/%d/%Y',), 
        widget=forms.DateInput(format='%d/%m/%Y', attrs={
            'class':'datePicker', 
            'size':'10'
        })
    )
         
        def __init__(self, *args, **kwargs):
                super(AddAtencionForm, self).__init__(*args, **kwargs)
                self.fields['persona_display'].label = "Autor"
                self.fields['alumno'].widget = forms.HiddenInput(attrs={'class':'form-control'}) # apago el  combo del cliente para que no se vea. :)
 
 


class AlumnoForm(forms.ModelForm):
        class Meta:
                model = Alumno
                exclude = ['user']

        nombreAlumno = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Nombre Alumno','size': '60'}))
        coloniaal = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Colonia alumno','size': '40'}))
        callenumal = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Calle y numero alumno','size': '40'}))
        localidadal = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Localidades alumno','size': '40'}))
        escuela_display = forms.CharField(max_length=180,widget=forms.TextInput(attrs={'placeholder':'Nombre de Escuela','size': '20','class':'form-control'}))
  

        def __init__(self, *args, **kwargs):
            super(AlumnoForm, self).__init__(*args, **kwargs)
            self.fields['escuela_display'].label = "Autor"
           # self.fields['escuela'].widget = forms.HiddenInput(attrs={'class':'form-control'}) # apago el  combo del cliente para que no se vea. :)
 


class AddEscuelaForm(forms.ModelForm):
        class Meta:
            model = Escuela
            exclude = ['user']
        
        colonia = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Colonia escuela','size': '40'}))
        direccion = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Direccion escuela','size': '40'}))
        localidad = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Localidades escuela','size': '40'}))

       
     
        
class LoginForm(forms.Form):

    username = forms.CharField(max_length=30, 
                widget = forms.TextInput(attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'Ingresa un nombre de usuario'
                    }))
    password = forms.CharField(max_length=30,
                widget = forms.TextInput(attrs = {
                    'type' : 'password',
                    'class' : 'form-control',
                    'placeholder' : 'Ingresa su contraseña'
                    }))

 

apps/principal/templates/principal/addEscuela.html
{% extends "base_principal.html" %}
{% block title %}Inicio{% endblock title %}
{% load static from staticfiles %}   

{% block content %}  

    {% include "principal/navbar.html" %} 

    <form class="form-horizontal" method="post">{% csrf_token %}    
                <div class="panel panel-primary">
                    <!-- <div class="panel-heading">Alumnos</div>  -->
                    <div class="panel-body">
                        <div class="page-header">
                            <br>
                        <h3>
                            <a href="/" class="btn btn-success">
                            <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                            </a>
                            <strong>Nueva Escuela</strong>
                        </h3>                                                        
                        </div><!-- page-header -->

                        <div class="row">                            
                            <div class="col-xs-12 col-sm-6"> 
                                <!-- Aqui  meti un inputo con  boton adjunto -->
                                <div class="form-group">                                 
                                     <label for="escuela" class="hidden-xs col-sm-2">Escuela:</label>
                                        <div class="input-group col-sm-10">     
                                            {{form.nombre}} 
                                            {{form.escuela_display}}
                                            {{form.escuela_display.error}}
                                            <span class="input-group-btn">
                                             <button class="btn btn-info btn-add" type="button">
                                                 <a href="{% url 'principal_app:add_alumno' %}">
                                                <span class="glyphicon glyphicon-plus"></span>Escuela </button>
                                                </a>
                                           
                                            </span> 
                                      </div>                                    
                                </div> 
 
                                                
                                <div class="form-group">
                                    <label for="colonia" class="hidden-xs col-sm-2">Colonia:</label>
                                    <div class="col-sm-10">
                                        {{form.colonia}}
                                        {{form.colonia.errors}}
                                    </div>
                                </div>  

                                <div class="form-group">
                                    <label for="direcccion" class="hidden-xs col-sm-2">Direccion:</label>
                                    <div class="col-sm-10">
                                        {{form.direccion}}
                                        {{form.direccion.errors}}
                                    </div>
                                </div>  
                                <div class="form-group">
                                    <label for="localidad" class="hidden-xs col-sm-2">Localidad:</label>
                                    <div class="col-sm-10">
                                        {{form.localidad}}
                                        {{form.localidad.errors}}
                                    </div>
                                </div>  

                                 <div class="form-group">
                                    <label for="turno" class="hidden-xs col-sm-2">Turno:</label>
                                    <div class="col-sm-10">
                                        {{form.turno}}
                                        {{form.turno.errors}}
                                    </div>
                                </div>          

                            </div> <!-- class="col-xs-12 col-sm-6" -->                           
                        </div> <!--<div class="row"> -->
                        

                        <div class="panel-footer color-footer">
                            <button type="submit" class="btn btn-primary">
                                 Grabar
                            </button>
                        </div>
 

                    </div>
                </div>
            </form>


   
 


<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
         $( document ).ready( function() {
          $("#id_escuela_display").autocomplete({
           source: '/auto_escuela',
           dataType: "jsonp",
           selectFirst: true,
           minLength: 4,
           select: function(event,ui) {
            $("#id_escuela").val(ui.item.id)
           }
          });
         });
 </script>

 

{% endblock content %}
  

apps/principal/templates/principal/addalumno3333.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    {% load static from staticfiles %}
  
    <link rel="stylesheet" href="{% static 'js/vendor/jquery-ui.css' %}"> 
    <script src="{% static 'js/vendor/jquery.js' %}"></script> 
    <script src="{% static 'js/vendor/jquery-ui.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-datepicker-es.js' %}"></script>

    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}     
    </form>    


<script>
    $('#id_fechaatencion').datepicker({ autoSize: true });
</script>

</body>
</html>

apps/principal/templates/principal/alumno_list.html
{% extends "base_principal.html" %}
{% block title %}Inicio{% endblock title %}
{% block content %} 
    {% include "principal/navbar.html" %} 

<div class="container">
        <div class="page-header">
            <br>
            <h4> 
                <br>
                <a href="/" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>             
                <a class="btn btn-primary pull-right" href="/addalumno">
                    <span class="glyphicon glyphicon-plus"></span> Nuevo Alumno
                </a>
            </h4>
        </div><!-- page-header -->
        <form  method="GET" enctype="multipart/form-data">{% csrf_token %} 
            <div class="row">
                <div class="col-md-4">
                    <div class="input-group">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                        <input type="text" name='q' class="form-control" placeholder="Busca por Nombre de Alumno">
                    </div>
                </div>
            </div>
        </form>
 

        <br>

          <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Sexo</th>
                        <th>Colonia</th>
                        <th>Direccion</th>
                        <th>Escuela</th>
                        <th>Fecha de Alta</th>
                        <th>Accion</th>
                    </tr>
                    </thead>
                    <tbody>
                       
                        
                        {%for a in alu %}
                        <tr>
                            
                            <td>
                               {{a.nombre}}
                            </td>
                             
                            <td>
                                {{a.sexo}}
                            </td>
                            <td>
                                {{a.coloniaal}}
                            </td>  
                            <td>
                                {{a.callenumal}}
                            </td>                           
                            <td>
                              {{a.escuela}}
                            </td>                             
                            <td>
                            {{a.fecha|date:"SHORT_DATE_FORMAT"}}
                            </td>
                            <td>
                                <td class="text-right">
                                
                                 <a href="#"  class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                            </td>                        
                        </tr>
                        {%endfor%} 
                        </tbody>
                </table>
            </div><!-- col-md-12 -->
        </div><!-- /row -->
    </div><!-- /container -->
      
{% endblock content %}

apps/principal/templates/principal/alumnosxx.html
{% extends "base_principal.html" %}
{% block title %}Inicio{% endblock title %}
{% block content %} 

        {% include "principal/navbar.html" %} 

<div class="container">
        <div class="page-header">
            <br>
            <br>
          <h4> 
           <a href="/" class="btn btn-success">
                            <span class="glyphicon glyphicon-chevron-left"></span> Regresar
            </a>             
            <a class="btn btn-primary pull-right" href="/addalumno">
                    <span class="glyphicon glyphicon-plus"></span> Nuevo Alumno
                </a>
          </h4>
        </div><!-- page-header -->

          <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Folio</th>
                        <th>Modalidad</th>
                        <th>Atencion</th>
                        <th>Alumno</th>
                        <th>Edad Meses</th>
                        <th>Sexo</th>
                        <th>Discapacidad</th>
                        <th>Escolaridad Grado</th>
                        <th>Escuela</th>
                        <th>FechaAtencion</th>
                        <th>User</th>
                    </tr>
                    </thead>
                    <tbody>
                        <h4><p>{{hospital}}</p></h4> 
                         <br>
                        
                        {%for a in alumnos%}
                        <tr>
                            <td>
                                 <small>{{a.folio}}</small>
                            </td>  
                             <td>
                                 <small>{{a.modalidad}}</small>
                            </td> 
                            <td>
                                <small>{{a.atencion}}</small>
                            </td>           
                            <td>
                                <small>{{a.nombre}}</small>
                            </td>
                            <td>
                               <small>{{a.edad}} {{a.meses}}</small>
                            </td>
                            <td>
                                <small>{{a.sexo}}</small>
                            </td>
                            <td>
                                <small>{{a.discapacidad}}</small>
                            </td>
                            <td>
                                <small>{{a.escolaridad}} {{a.grado}}</small>
                            </td>                            
                            <td>
                                <small>{{a.escuela}}</small>
                            </td>
                            <td>
                                <small>{{a.fechaatencion|date:"M d, Y"}}</small>
                            </td>
                            <td>
                                <small>{{a.user }}</small>
                            </td>
                            <td>
                                <td class="text-right">                                
                                <a href="{% url 'principal_app:alumno_update' a.id %}"  class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                            </td>                        
                        </tr>
                        {%endfor%} 
                        </tbody>
                </table>
            </div><!-- col-md-12 -->
        </div><!-- /row -->
    </div><!-- /container -->
      
{% endblock content %}

apps/principal/templates/principal/base_principalzzzz.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}	
	{% load static from staticfiles %}    
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">	
    <link rel="stylesheet" href="{% static 'css/sb-admin.css' %}">
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'js/vendor/jquery-ui.css' %}">   
{% endblock css %}

{% block js %}  
	<script src="{% static 'js/vendor/jquery.js' %}"></script> 
	<script src="{% static 'js/vendor/jquery-ui.js' %}"></script>
	<script src="{% static 'js/vendor/jquery-datepicker-es.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap.js' %}"></script>
{% endblock js %}
	 
    <!--
	<cript src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 	-->

	<!-- Latest compiled and minified CSS -->
	<!--
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	-->

	<!-- Optional theme -->
	<!--
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	-->

	<!-- Latest compiled and minified JavaScript -->
	<!--
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 	-->
	    
	<!-- Bootstrap Core JavaScript  
		<script scr="{% static 'js/vendor/jquery.js' %}"></script>
	    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'js/bootstrap.js' %}"></script>

	-->
 

 

apps/principal/templates/principal/dorado.html
#ok, en el popup pongo este codigo 
<form class="taskForm form-horizontal" role="form">
    <input type="hidden" id="max_percentage" value="{{config.MAX_GRADE_EQUIVALENCE}}"/>
	<div class="form-group">
		<label class="col-sm-3 control-label" for="task_name">{% trans "Name" %}:</label>
		<div class="col-sm-9">
			<input class="form-control" type="text" id="task_name" placeholder='{% trans "Name" %}' {% if task %} value="{{ task.name }}"{% endif %}/>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label" for="task_description">{% trans "Description" %}:</label>
		<div class="col-sm-9">
			<textarea class="form-control" id="task_description" placeholder='{% trans "Description" %}'>{% if task %}{{ task.description }}{% endif %}</textarea>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label" for="task_percentage">{% trans "Approbation grade" %}:</label>
		<div class="col-sm-9">
			<input class="form-control" type="text" id="task_percentage" maxlength="4" placeholder='{% trans "Approbation grade" %}' {% if task %} value="{{ task.convert_percentage }}"{% endif %}/>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label" for="task_editable">{% trans "Allow replacement task" %}:</label>
		<div class="col-sm-9">
			<input type="checkbox" id="task_editable" value="true">
		</div>
	</div>
</form>

//// en el js pongo esto///

$('.editTask').click(function(event) {
		var task_id = $(this).attr("task");
		var module_id = $(this).attr("module");
		
		taskModal = bombModal(null, {
			ajax: homeURL + "lms/courses/task/" + task_id + "/open_popup_task/",
			title: "Editar tarea",
			answers: {
								"Guardar": function(response,theDiv){
								var task = new Task();
								task.id = task_id
								task.name = theDiv.find("#task_name").val();
								task.description = theDiv.find("#task_description").val();
								task.percentage = parseInt(theDiv.find("#task_percentage").val());
								max_percentage = parseInt(theDiv.find("#max_percentage").val());
                                if ((max_percentage > 0) && task.percentage > max_percentage){     
                                    alert("No puede escribir un porcentaje mayor a " + max_percentage);
                                    return false;
                                }
                                else{
								    task.editable = theDiv.find('#task_editable').val();
								    task.module_id = module_id;
								    saveTask(task);
								    return false;
                                }

							}
				}
		});
	});

task_name = request.POST.get("task_name", None)
    task_percentage = request.POST.get("task_percentage", None)
    task_description = request.POST.get("task_description", None)
    task_module_id = request.POST.get("module_id", None)
    task_editable = request.POST.get('task_editable', None)



def popup_manage_course(request, course_id=None):
    t = Course.objects.get(pk=course_id)
    if t.versioncourse.version_type == 'group':
        s = GroupAdvancedForm(instance=t)
    else:
        s = CourseAdvancedForm(instance=t)
    variables = RequestContext(request, {
        "course" : t,
        "courseForm": s,
        "vcourse": t.versioncourse,
        "app_name": APP_NAME,
    })

    return render_to_response("quest/lms/popup_manage_course.html", variables)

   <form class="form-horizontal well" data-async data-target="#myModal" action="thanks/" method="POST">
              
   <form class="form-horizontal well" data-async data-target="#myModal" action="index/" method="POST"> 
   <form class="form-horizontal well" data-async data-target="#myModal" action="index/" method="POST">  

apps/principal/templates/principal/navbar.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
             <a class="navbar-brand"  href="#">Parepe Laguna</a>
        </div>
        
        

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                <li><p class="navbar-text">Bienvenido, <a href="#" class="navbar-link">{{ user.username|capfirst}}</a></p></li>
                  <li><a href="{% url 'users_app:logout' %}">Cerrar</a></li>                 
                
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

apps/principal/templates/principal/noactivo.html
{% extends "base_principal.html" %}

{% block title %}Usuario desactivado{% endblock title %}
 

{% block content %}
<p class="bg-danger">El usuario no esta activo: Contactarse con el administrador, para resolver el problema</p>
{% endblock content %}

apps/principal/templates/principal/nousuario.html
{% extends "base_principal.html" %}

{% block title %}Error de acceso {% endblock title %}
 
{% block content %}
	<p class="bg-danger">Error de acceso: El usuario y la contraseña no coinciden o no existen</p>
{% endblock content %}